### PR TITLE
compact some code

### PR DESCRIPTION
**Pull request by eumiro**
A few random refactorings to compact the code and hopefully improve readability. All of them are consistent within their methods, so please feel free to pick up what you like.

And I am wondering why the filenames are Capitalized. Can do a separate PR if you wish.

### CODE REVIEW

**Comment by fdw** [comment]
Hey, thank you again 🙂

There are definitely some changes I'd like to merge, but not all of them. How should proceed? Should I make a new commit (under your name) with just the changes I want, or should I merge all and then undo some? Do you have a preference?

Regarding the names: That's not on purpose, either my IDE decided for me or it's a habit from Java/Kotlin 😉 I'm not sure if it hurts, though.

**Comment by eumiro** [comment]
Happy to hear that, thank you. You can add a new commit to my branch where you undo what you don't want to have then we can squash the two commits.

For filenames please see https://www.python.org/dev/peps/pep-0008/#package-and-module-names
When we're done here, I can prepare another small PR.

**Comment by fdw** [comment]
I've made my changes, happy squashing :)

About the names, following the standard makes obviously sense. If you want to, change them and add them to this PR.

**Comment by eumiro** [comment]
done and done :+1:

**Comment by fdw** [comment]
Perfect, thank you very much :)

But I have one last request: I think the module name in `setup.py` shoul also be lower case.

**Comment by eumiro** [comment]
Good catch! Done.

**Comment by fdw** [comment]
Thanks again for improving my Python 🙂

**Pull request merged**
