### PR TITLE
fixed extract_emojis.py url and updated emojis in rofimoji.py

### PR DESCRIPTION
**Pull request by Heholord**

### CODE REVIEW

**Comment by fdw** [comment]
Hi @Heholord , thanks for your PR! :)

However, I'm not sure what you fixed - the old version still seems to work fine for me. Are there any emojis missing from the big list that you now included? Are there any other problems?

**Comment by Heholord** [comment]
Hey @fdw ,

Ah the old url: https://emojipedia.org/emoji/ still works for you? For some reasons I can't access it.

**Comment by fdw** [comment]
Ah, okay.

Do you think it would make sense to use your implementation as a backup if the main URL is not working? Or should I just close this PR?

**Comment by Heholord** [comment]
Now I have hard times accessing the page again but i'll leave the decision to you. Anyway thanks for that awesome tool 😌

**Comment by fdw** [comment]
Thank you 😄

I have problems accessing the site now, too. Fortunately, it's only required for updating the emojis, which shouldn't happen too often.
However, I'll think about it a bit. Maybe there is a library I can use instead of collecting them manually?

**Pull request closed without merging**
