### PR TITLE
man page: fix double-dashes in option names

### PR DESCRIPTION
**Pull request by Rogach**
Apparently by default pandoc interprets "--" as an em-dash, and resulting man page contains a single dash instead of two (e.g. `-files` instead of `--files`).

Running pandoc as follows:

```
pandoc -s -f markdown-smart -t man rofimoji.1.md -o rofimoji.1
```

seems to fix the issue. Unfortunately we lose the pretty directional double quotes, but I believe that the only way to fix the double-dashes and to keep the pretty quotes is to edit the man page source manually.

### CODE REVIEW

**Comment by fdw** [comment]
Thanks for finding that! I had a look at pandoc's examples, and it seems there is a solution: The first `-` needs to be escaped, so for example `\--skin-tone`. This also seems to work for me. What do you think? If you like it, do you want to update your PR, or should I?

**Comment by Rogach** [comment]
Yes, escaping is also an option. I initially decided against it because it could be easy to forget to escape it somewhere (in the future updates), but if you prefer the explicit escapes then it's also fine (and we get back the pretty quotes as well).

I'll update the PR tomorrow.

**Comment by fdw** [comment]
I think I do prefer escaping, as it's quite easy to forget the `-f markdown-smart` option, too 😉

**Comment by Rogach** [comment]
Updated.

> quite easy to forget the -f markdown-smart option, too

I usually use makefiles to run simple housekeeping tasks, for example in this case I used the following makefile:

```
src/picker/docs/rofimoji.1: src/picker/docs/rofimoji.1.md
	pandoc -s -t man src/picker/docs/rofimoji.1.md -o src/picker/docs/rofimoji.1
```

**Comment by fdw** [comment]
Makes sense, thanks for the idea :)

**Pull request merged**
