### PR TITLE
😈 is a devil

### PR DESCRIPTION
**Pull request by ncfavier**

### CODE REVIEW

**Comment by fdw** [comment]
Hey, thanks for the PR 🙂

Unfortunately, these files are automatically generated from the official Unicode documentation. So any changes here will be wiped the next time I update everything.
However, you could add the entry to `src/picker/data/additional/emojis_smileys_emotion.csv` (which doesn't exist yet, but feel free to create it). Then it will be loaded automatically and not overwritten on updates.

**Comment by ncfavier** [comment]
Like this?

**Comment by fdw** [comment]
Almost - the descriptions will be appended, so you don't need to repeat the original one. Just leave your new annotations, and it should work 🙂

**Comment by fdw** [comment]
Hey, I'm sorry you closed this PR. Could I have done anything better? Do you want me to add your changes (with you as co-author, of course)?

**Comment by ncfavier** [comment]
I expected this to be a trivial 1-minute fix and not to have to set up any infrastructure. It's fine, I just don't care enough. Do what you want.

**Comment by fdw** [comment]
I see, thank you 🙂 Unfortunately, you were the first person to improve the descriptions with the new setup, so there was nothing to use as an example.

I think I'll take your changes to make it easier for the next person.

Thank you and have a good day 🙂

**Pull request closed without merging**
