### PR TITLE
Fix help option

### PR DESCRIPTION
**Pull request by polyzen**
`TypeError: sequence item 0: expected str instance, PosixPath found`

Not sure if this is the most idiomatic solution, but it works.

### CODE REVIEW

**Comment by katacarbix** [comment]
I'm not really sure what the issue you're having is, but this works on my system.

**Comment by polyzen** [comment]
```
~ > rofimoji -h
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 339, in main
    Rofimoji()
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 51, in __init__
    self.args = self.parse_arguments()
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 146, in parse_arguments
    parsed_args = parser.parse_args()
  File "/usr/lib/python3.9/site-packages/configargparse.py", line 451, in parse_args
    args, argv = self.parse_known_args(args = args,
  File "/usr/lib/python3.9/site-packages/configargparse.py", line 613, in parse_known_args
    namespace, unknown_args = argparse.ArgumentParser.parse_known_args(
  File "/usr/lib/python3.9/argparse.py", line 1851, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 2060, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.9/argparse.py", line 2000, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.9/argparse.py", line 1928, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.9/argparse.py", line 1092, in __call__
    parser.print_help()
  File "/usr/lib/python3.9/argparse.py", line 2548, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python3.9/site-packages/configargparse.py", line 905, in format_help
    msg += " (%s)." % " or ".join(tuple(default_config_files) +
TypeError: sequence item 0: expected str instance, PosixPath found
```

**Comment by fdw** [comment]
Thanks for the fix!

I'm wondering if `configargparse` is worth it, or if `rofimoji` should move to a separate config file...

**Comment by polyzen** [comment]
I see `argparse` is also imported, but I don't see any changes after removing its usage. Could be nice to have no dependencies outside of the standard library. Could easily do without the `xdg` module: https://stackoverflow.com/a/53222876

**Comment by fdw** [comment]
I've just removed pyxdg, as that was already annoying 🙂

`argparse` is only needed for type hints because `configargparse` is completely compatible with it. Maybe we can replace that with something else, but I don't think I want to roll my own config file parser (as nice as having no dependencies would be).

**Comment by polyzen** [comment]
https://docs.python.org/3/library/configparser.html

**Pull request merged**
